"""empty message

Revision ID: 5173e3f43d28
Revises: 24b2e039c38a
Create Date: 2025-06-28 18:31:54.868230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5173e3f43d28'
down_revision = '24b2e039c38a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('delivery_address', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pickup_point', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_column('pickup_point')
        batch_op.drop_column('delivery_address')

    # ### end Alembic commands ###
